# Site
repository: deexxter/honchukov.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Oleh Honchukov
title: Devops Engineer
email: jaykey@ukr.net
phone: +380 95 764 67 74
age: 30


# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  deexxter
facebook_username: honchukov
instagram_username: o.honchukov
linkedin_username: ohonchukov

# Theme settings
# Additional icon links
#additional_links:
#- title: google.com
#  icon: fas fa-globe
#  url: https://deexxter.github.io/honchukov.github.io/

# About Section
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Oleh and I'm a DevOps(Linux) Engineer 5 years of experience. Not afraid to learn something new and ready to do everything possible to achieve a result.
  Learning DevOps practices.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project my CV
        link: github.com/deexxter
        additional_links:
          - title: honchukov.github.io
            icon: fab fa-github
            url: github.com/deexxter/honchukov.github.io
        description: | # this will include new lines to allow paragraphs
          I started this project as a way of learning and it has since grown into a fully fledged app. Through this project, I have demonstrated my skills and capabilities, making it a significant part of my portfolio. My resume itself showcases my expertise and experience, reflecting my journey and accomplishments in the field.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
        - layout: left
          title: "PINUP.TECH"
          link: https://pin-up.global/
          link_text: pin-up.global
          sub_title: Junior Devops Engineer
          caption: January 2022 - Present
          description: | # this will include new lines to allow paragraphs
           
            - Linux (CentOS, Debian) installation, configuration, and administration.
            - AWS Cloud (EC2, S3, VPC, IAM, Route53, CloudWatch, Lambda, etc.)
            - AWX (Ansible Tower)
            - IaC basic (Ansible, Terraform) 
            - Git CI (Gitlab, Github)
            - Docker
            - Python (basic), bash
            - Monitoring (Zabbix, Grafana, Prometheus)
            - Borg backup
            - Administration of oVirt, KVM 
            - Optimizing and writing bash scripts 
            - Administration of Zabbix and incident response

        - layout: left
          title: "Ves-Ukraine"
          link: 
          link_text: 
          sub_title: System Administrator
          caption: May 2020 - January 2022
          description: | # this will include new lines to allow paragraphs
            - Domain Controllers Administration 
            - Bitrix24 Administration 
            - Management of the company network 
            - Administration of ESXI, Hyper-V servers 
            - Linux servers administration 
            - Optimizing and writing bash\powershell scripts 
            - Administration of zabbix and incident response
  
        - layout: left
          title: "E-TENDER LLC"
          link: 
          link_text: 
          sub_title: System Administrator
          caption: June 2019 - November 2019
          description: | # this will include new lines to allow paragraphs
            - Office365 cloud administration 
            - Domain Controller administration 
            - Bitrix24 administration 
            - ACS administration 
            - ESXI server administration 
            - NAS administration
  
        - layout: left
          title: 8Color
          link: 
          link_text: 
          sub_title: Senior System Administrator
          caption: March 2018 - May 2019
          description: | # this will include new lines to allow paragraphs
            - Maintenance of information system on Microsoft platform
            - Microsoft system support 
            - Linux system support 
            - Working with NAS Synology \ Qnap 
            - Working with VMware \ Hyper-V 
            - Working with Dahua video surveillance systems
  
        - layout: left
          title: Tim Berners Group Ukraine LLC
          link: 
          link_text: 
          sub_title: WiFi Data services (system administrator)
          caption: November 2016 - March 2018
          description: | # this will include new lines to allow paragraphs
            - Technical support: managing the service monitoring system, responding to customer requests, finding and troubleshooting 
            - Connecting services for new customers: deploying virtual machines, setting up hotspots, registering them on the web portal 
            - Working in Linux systems 
            - Working in Mikrotik RouterOS, ddwrt 
            - Organizing data channels for customers
  


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: State University of Information and Communication Technologies

        caption: 2014 - 2016
        sub_title: Computer engineering
        description: | # this will include new lines to allow paragraphs
          Kyiv University

      - layout: left
        title: Communication College
        caption: 2010 - 2014
        sub_title: Computer engineer
        description: | # this will include new lines to allow paragraphs
          Kyiv, Unfinished higher education

  - title: Additional Education and Certificates
    layout: list
    content:
      - layout: left
        description: CISCO CCNA 
        caption: 2013 - 2014
      - layout: left
        description: Skillbox Devops practice
        caption: 2021
      - layout: left
        description: Red Hat Linux Fundamentals
        caption: 2022
        



  - title: Languages
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Ukrainian: fluent
      - Russian: fluent
      - English: average

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in DevOps and software engineering some of my other interests and hobbies are:
        - Vespa scooters
        - Traveling
        - Gaming

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag